pipeline {
    agent {
        node {
            label 'PACKER'
        }
    }

    stages {
        stage('Packer Version') {
            steps {
                sh 'ls -la && packer --version' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd packer && packer validate -var-file=./config/default.json master.json'
            }
        }
        stage('Build') {
            steps {
                sh 'cd packer && packer build -var-file=./config/default.json master.json'
            }
        }
        stage('Updating the build AMI') {
            environment {
                AMI_ID = "${sh(script:'jq -r \'.builds[-1].artifact_id\' packer/manifest.json | cut -d \":\" -f2', returnStdout: true).trim()}"
            }
            steps {
                dir('packer') {
                     echo "AMI_ID = ${env.AMI_ID}"
                     sh "aws --region us-west-2 ec2 create-launch-template-version --launch-template-name ricardo-test-launchtemplate --version-description \"new version ${env.AMI_ID}\"  --launch-template-data '{\"ImageId\":\"${env.AMI_ID}\"}'"
                     sh "aws --region us-west-2 autoscaling start-instance-refresh --auto-scaling-group-name us2-dev-tomcat-asg --preferences MinHealthyPercentage=100,InstanceWarmup=120"
                }
            }
        }
    }
}