pipeline {
    agent {
        node {
            label 'PACKER'
        }
    }

    stages {
        stage('Packer Version') {
            steps {
                sh 'ls -la && packer --version' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd packer && packer validate -var-file=./config/default.json master.json'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}