pipeline {
    agent {
        node {
            label 'PACKER'
        }
    }

    stages {
        stage('Packer Version') {
            steps {
                sh 'ls -la && packer --version' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd packer && packer validate -var-file=./config/default.json master.json'
            }
        }
        // stage('Build') {
        //     steps {
        //         sh 'cd packer && packer build -var-file=./config/default.json master.json'
        //     }
        // }
        stage('Updating the build AMI') {
            steps {
                sh 'cd packer'
                sh 'ls -la'
            }
        }
    }
}