
name: act poc
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: ahmadnassri/action-workflow-queue@v1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Add hosts to /etc/hosts
      run: |
        sudo echo "127.0.0.1 dev-portal.include.com" | sudo tee -a /etc/hosts
    - name: Install  pip
      run: |
        nslookup dev-portal.include.com
        sleep 60

    - name: Install  pip
      run: |
        python -m pip install --upgrade setuptools pip wheel py-make
        
