name: "Github Action: push backend site"
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read 

jobs:
  development:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test cli
        run: |
          pip3 install chalice --upgrade
          chalice --help
          echo "app-$GITHUB_SHA"
