name: Test-Workflow

on:
  push:
    tags:
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
        #run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: testing
        run: echo $RELEASE_VERSION
      - name: ls current dir
        run: ls
      # - name: uploading zip
      #   uses: ItsKarma/aws-cli@v1.70.0
      #   with:
      #     args: s3 sync --delete --acl public-read localdir/ s3://remote-bucket/
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: "us-east-1
