name: "Github Action: deploy portalapi"
on:
  push:
    branches:    
      - "demo"
      - "master"
  pull_request:
    types: [closed]
    branches:    
      - "master"
    paths:
      -  "helloworld/**"

defaults:
  run:
    working-directory: ./helloworld

permissions:
  id-token: write
  contents: read 

jobs:
  build:
    uses: ./.github/workflows/verify.yml

  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    uses: ./.github/workflows/deploy.yml
