name: "Github Action: deploy portalapi"
on:
  push:
    branches:    
      - "demo"
    paths:
      -  "helloworld/**"
  pull_request:
    types: [closed]
    branches:    
      - "master"
    paths:
      -  "helloworld/**"

defaults:
  run:
    working-directory: ./helloworld

permissions:
  id-token: write
  contents: read 

jobs:
  build:
    uses: ./.github/workflows/verify.yml
    with:
      environment: dev

  # deploy:
  #   if: github.event.pull_request.merged == true
  #   needs: build
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Setup Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: "3.9"

  #   - name: Install  pip
  #     run: |
  #       python -m pip install --upgrade setuptools pip wheel py-make
  #       ls -la