name: "Github Action: push backend site"
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read 

jobs:
  development:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: test cli
        run: |
          pip3 install 'awsebcli==3.20.3' --upgrade
          echo "app-$GITHUB_SHA"
          eb --version
      - name: Check URL endpoint
        uses: jtalk/url-health-check-action@v2
        with:
          url: "{{ secrets.HEALTH_URL }}"
          max-attempts: 3
          retry-delay: 5s
