name: Test-Workflow

on:
  push:
    tags:
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag-value
        uses: dawidd6/action-get-tag@v1
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ${{steps.tag-value.outputs.tag}}.zip .
      - name: Upload files
        uses: docker://amazon/aws-cli:latest
        with:
          args: s3 cp ${{steps.tag-value.outputs.tag}}.zip  s3://ricardo-nclouds-bucket/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
