name: Self Hosted - 3
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: build packages
      run: ls -la && sleep 15
    - name: docker
      run: docker --version
    - name: docker build
      run: docker build -t example .
