name: verify portalapi

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install  pip
      env:
        ENVIRONMENT: ${{ inputs.envr }}
      run: |
        echo $ENVIRONMENT
        python -m pip install --upgrade setuptools pip wheel py-make
        echo "before sleep"
        sleep 15
        echo "after sleep"
        aws --version
