jenkins:
  systemMessage: "RICARDO LO LOGRASTE"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "Administrators"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - ${ADMIN_USER}
              - test-user
          - name: "Triggers"
            description: "Triggers for builds"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
              - "Agent/Build"
            assignments:
              - lambda
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${ADMIN_USER}
          password: ${ADMIN_PASSWORD}
        - id: lambda
          password: lambda
        - id: ricardo
          password: ricardo
          